# Generated by Django 3.0.4 on 2020-06-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='chiffre_affaire',
            field=models.FloatField(default=0),
        ),
    ]
