# Generated by Django 3.0.4 on 2020-06-14 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0004_auto_20200614_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='fournisseur',
        ),
        migrations.DeleteModel(
            name='Fournisseur',
        ),
    ]
